### PR TITLE
[WIP]use scripted Jenkinsfile to solve version bump issue

### PR DESCRIPTION
**Pull request by pydevops**

### CODE REVIEW

**Comment by chrislovecnm** [comment]
CI failed

**Comment by pydevops** [comment]
The CI failed due to "Upgrading control plane to version 1.10.4
ERROR: (gcloud.container.clusters.upgrade) ResponseError: code=400, message=No valid versions with the prefix "1.10.4" found.".

**Comment by chrislovecnm** [comment]
test this please

**Comment by pydevops** [comment]
test this please

**Comment by pydevops** [comment]
- I have fixed the version issue by picking up the top 2 master versions instead of 1 from first and 1 from the last one (out of the array list of validMasterVersion). 
- expand-contract-upgrade validation failed at "Check the number of client nodes", which needs to be investigated further.

**Comment by chrislovecnm** [comment]
@pydevops can you rebase?

**Pull request merged**
