### PR TITLE
[WIP] Fixing Teardown script to make sure it deletes PVs and cluster in fin…

### PR DESCRIPTION
**Pull request by homernajafi**
Removing PVs during Teardown and also wait for cluster to be upgraded before deleting it (in Jenkins Finally block)

### CODE REVIEW

**Comment by homernajafi** [comment]
Test this please

**Comment by homernajafi** [comment]
Test this please

**Comment by chrislovecnm** [comment]
test this please

**Comment by homernajafi** [comment]
test this please

**Comment by homernajafi** [comment]
test this please

**Comment by chrislovecnm** [comment]
Can you clean this up, want to get probably just this merged

**Comment by chrislovecnm** [comment]
Test this please

**Comment by raddaoui** [comment]
ok to test

**Pull request merged**
